### ISSUE TITLE
RQDA installation wizard error

### ISSUE THREAD

**Issue by Jhonattan38G** [BroVic/RQDAassist#3]
Hi Victor, the error that I mentioned to you in the RQDA repository, it appears the same with the installation of the RQDA assistant, look at the error.
any ideas?
```R
> devtools::install_github("BroVic/RQDAassist")
Downloading GitHub repo BroVic/RQDAassist@HEAD
Error: Failed to install 'RQDAassist' from GitHub:
  create process 'C:/PROGRA~1/R/R-41~1.1/bin/x64/Rcmd.exe' (system error 267, El nombre del directorio no es válido.
) @win/processx.c:1040 (processx_exec)
> devtools::install_github("BroVic/RQDAassist",verbose = TRUE)
Downloading GitHub repo BroVic/RQDAassist@HEAD
Error: Failed to install 'RQDAassist' from GitHub:
  create process 'C:/PROGRA~1/R/R-41~1.1/bin/x64/Rcmd.exe' (system error 267, El nombre del directorio no es válido.
) @win/processx.c:1040 (processx_exec)
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `verbose`

Did you misspecify an argument? 
```

**Comment by BroVic** [comment]
Do you have **Rtools40** installed and on System PATH? To check this, run `pkgbuild::has_build_tools()` and if it returns `FALSE`, go to CRAN to get it.

**Comment by Jhonattan38G** [comment]
Yes, I have the RTools40 tool installed, but I have not verified if it appears in FALSE with
```R
pkgbuild :: has_build_tools ()
```
But I already did its previous installation, maybe I will also check that Victor, I will be writing to you these days to the mail, but if you find information regarding that error and a possible solution, since in several forums I have noticed that they have not found a sufficient solution.

**Comment by BroVic** [comment]
@Jhonattan38G 

I will definitely look at it. Cheers.

**Comment by BroVic** [comment]
@Jhonattan38G 

For the record, this is not an issue with the package, but has something to do with your particular R installation. I removed RQDAassist in an attempt to reproduce your problem, but it installed fine on my computer. I also removed RQDA and all its direct dependencies (i.e. RGtk2, gWidgets, gWidgetsRGtk2) from my computer and tried to reinstall. Everything worked just fine.

I did a quick search of your error and found [this StackOverflow question](https://stackoverflow.com/questions/68400661/r-unable-to-install-packages-from-github-system-error-267-win-processx-c1040). You should look at it - I believe the answer to your problem lies there. Feel free to open a new issue if you encounter further challenges.

Good luck!
